Repository openlawlibrary/python-docx, pull requests merged in 2019-01, with the labels that each got.

#10 autonumbering updates and fixes
  docx/oxml/numbering.py
  docx/oxml/text/paragraph.py
  docx/oxml/text/parfmt.py
  docx/parts/document.py
  docx/text/paragraph.py
Labels: bug, enhancement

#2 OLL specific: Display parsed number in paragraph representation.
  docx/text/paragraph.py
Labels: enhancement

#8 inline content controls
  docx/oxml/text/paragraph.py
  docx/text/paragraph.py
Labels: enhancement

#12 Fix for getting level of non-numbered paras.
  docx/text/paragraph.py
Labels: bug

#13 igord/autonumbering fix
  docx/text/paragraph.py
Labels: bug

#4 list item indent
  docx/blkcntnr.py
  docx/document.py
  docx/oxml/numbering.py
  docx/oxml/text/paragraph.py
  docx/text/paragraph.py
Labels: enhancement

#14 updated version to 0.8.7
  docx/__init__.py
Labels: enhancement

#16 added missing roman lib dependency
  requirements.txt
  setup.py
Labels: bug

#17 merge image content type fix
  docx/image/image.py
Labels: bug
