Repository openlawlibrary/python-docx, pull requests merged in 2019-03, with the labels that each got.

#18 para access normalized indentation
  docx/text/paragraph.py
Labels: enhancement

#20 Rework and fix of `norm_para_indent` paragraph method
  docx/text/paragraph.py
Labels: bug, enhancement

#23 para mix indent
  docx/text/paragraph.py
Labels: bug, enhancement

#21 update version to 0.8.8
  docx/__init__.py
Labels: enhancement

#24 added support for ordinary ms word numbering
  docx/oxml/numbering.py
Labels: bug

#25 ordinary autonumbering merge into merge-all
  docx/oxml/numbering.py
Labels: bug
